name: Build Kiryuu Extension

on:
  push:
    branches: [ master, main ]
    paths:
      - 'src/id/kiryuu/**'
      - 'lib/**'
      - 'build.gradle*'
      - 'settings.gradle*'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'src/id/kiryuu/**'
      - 'lib/**'
  workflow_dispatch:

jobs:
  build-kiryuu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Local Libraries
      run: |
        echo "Building local extension library..."
        ./gradlew :lib-extension:publishToMavenLocal --no-daemon
        ./gradlew :lib-ratelimit:publishToMavenLocal --no-daemon
        ./gradlew :duktape-stub:publishToMavenLocal --no-daemon  
        ./gradlew :preference-stub:publishToMavenLocal --no-daemon
        
    - name: Build Kiryuu Extension (Skip lint)
      run: ./gradlew :id-kiryuu:assembleRelease -x lint --no-daemon
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kiryuu-extension
        path: src/id/kiryuu/build/outputs/apk/release/*.apk
        retention-days: 30
        
    - name: Get APK info
      run: |
        APK_PATH=$(find src/id/kiryuu/build/outputs/apk/release -name "*.apk" | head -1)
        if [ -f "$APK_PATH" ]; then
          echo "APK built successfully: $APK_PATH"
          ls -la "$APK_PATH"
        else
          echo "APK not found!"
          exit 1
        fi