name: Build Tachiyomi extension (legacy Gradle 5.4.1)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # sesuaikan jika project membutuhkan SDK / build-tools lain
  ANDROID_COMPILE_SDK: "28"
  BUILD_TOOLS_VERSION: "28.0.3"
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx1536m"

jobs:
  build:
    name: Build (legacy gradle)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          # kunci cache termasuk gradle-wrapper.properties agar berganti bila wrapper berubah
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle*','**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 8 (compatible with Gradle 5.x / older Android builds)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '1.8'
          cache: 'gradle'

      - name: Set ANDROID_HOME
        run: |
          echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/usr/local/android-sdk" >> $GITHUB_ENV
          mkdir -p /usr/local/android-sdk

      - name: Setup Android SDK (install platform-tools, platform, build-tools)
        uses: r0adkll/setup-android@v2
        with:
          api-levels: ${{ env.ANDROID_COMPILE_SDK }}
          build-tools: ${{ env.BUILD_TOOLS_VERSION }}
          target: default
          ndk: false

      - name: Show java and gradle versions
        run: |
          java -version || true
          chmod +x ./gradlew || true
          ./gradlew --version || true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (assembleRelease)
        # Jika modul spesifik yang harus dibuild, ganti ./gradlew assembleRelease jadi ./gradlew :modul:assembleRelease
        run: |
          # Jika build jadul sering gagal karena lint/keamanan, skip lint agar build tetap lanjut.
          ./gradlew assembleRelease -x lint --no-daemon --stacktrace
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          GRADLE_OPTS: ${{ env.GRADLE_OPTS }}

      - name: Collect build outputs
        run: |
          echo "List possible outputs:"
          find . -type f -name "*.apk" -o -name "*.aar" -o -name "*.jar" || true
          # show build logs location if needed
          ls -la **/build/ || true

      - name: Upload artifact (APK / AAR / JAR)
        uses: actions/upload-artifact@v4
        with:
          name: extension-build
          path: |
            **/build/outputs/**/*.apk
            **/build/outputs/**/*.aar
            **/build/libs/*.jar
            **/build/outputs/**/*.ap_ || true

