name: Build single extension (src/<lang>/<extension> layout)

on:
  workflow_dispatch:
    inputs:
      lang:
        description: Extension language folder (contoh: en, id, es)
        required: true
        default: 'id'
      extension:
        description: Extension folder/name (contoh: mangadex, komiku)
        required: true
      git-repo:
        description: Git repo (owner/repo). Optional, default: current repo
        required: false
        default: ''
      git-ref:
        description: Git Ref to checkout (branch / tag / sha)
        required: false
        default: 'main'
      buildType:
        description: Build variant
        required: true
        type: choice
        options:
          - Debug
          - Release
        default: Debug

env:
  ANDROID_COMPILE_SDK: "28"        # ubah bila butuh SDK lain
  BUILD_TOOLS_VERSION: "28.0.3"    # ubah sesuai kebutuhan

jobs:
  build-extension:
    runs-on: ubuntu-latest
    name: Build extension from src layout

    steps:
      - name: Checkout repo (possibly other repository)
        uses: actions/checkout@v4
        with:
          # jika input git-repo dikosongkan, checkout repo saat ini
          repository: ${{ github.event.inputs.git-repo != '' && github.event.inputs.git-repo || github.repository }}
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Show repo summary (debug)
        run: |
          echo "Checked out: $(git rev-parse --abbrev-ref HEAD || git rev-parse --short HEAD)"
          echo "ls root:"
          ls -la

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: 'gradle'

      - name: Setup Android SDK (if needed)
        uses: android-actions/setup-android@v3
        with:
          api-levels: ${{ env.ANDROID_COMPILE_SDK }}
          build-tools: ${{ env.BUILD_TOOLS_VERSION }}
          components: "platform-tools,platforms;android-${{ env.ANDROID_COMPILE_SDK }}"

      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew || true
          ./gradlew --version || true

      - name: Detect module and build
        id: build
        env:
          LANG_IN: ${{ github.event.inputs.lang }}
          EXT_IN: ${{ github.event.inputs.extension }}
          BUILD_TYPE: ${{ github.event.inputs.buildType }}
        run: |
          set -euo pipefail
          echo "Inputs: lang='${LANG_IN}', extension='${EXT_IN}', buildType='${BUILD_TYPE}'"
          MODULE_NAME=":${LANG_IN}-${EXT_IN}"
          SRC_DIR="src/${LANG_IN}/${EXT_IN}"

          echo "Expect module path: ${MODULE_NAME}"
          echo "Expect project dir: ${SRC_DIR}"

          if [ -d "${SRC_DIR}" ]; then
            echo "Found directory ${SRC_DIR} — will build module ${MODULE_NAME}"
          else
            echo "ERROR: Directory ${SRC_DIR} not found. Check inputs or repository layout."
            echo "Contents of src/:"
            ls -la src || true
            exit 1
          fi

          # run assemble task from root using module path
          TASK="assemble${BUILD_TYPE}"
          echo "Running: ./gradlew ${MODULE_NAME}:${TASK} -x lint --no-daemon --stacktrace"
          ./gradlew "${MODULE_NAME}:${TASK}" -x lint --no-daemon --stacktrace

          echo "Build step finished."

      - name: List generated outputs (debug)
        run: |
          echo "Looking for outputs under src/${{ github.event.inputs.lang }}/${{ github.event.inputs.extension }}/build/ and general build outputs"
          find "src/${{ github.event.inputs.lang }}/${{ github.event.inputs.extension }}/build" -maxdepth 5 -type f -name "*.apk" -o -name "*.aar" -o -name "*.jar" || true
          find . -type f -name "*.apk" -o -name "*.aar" -o -name "*.jar" || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.lang }}-${{ github.event.inputs.extension }}-${{ github.event.inputs.buildType }}
          path: |
            src/${{ github.event.inputs.lang }}/${{ github.event.inputs.extension }}/build/outputs/**/*.apk
            src/${{ github.event.inputs.lang }}/${{ github.event.inputs.extension }}/build/outputs/**/*.aar
            **/build/outputs/**/*.apk
            **/build/outputs/**/*.aar
            **/build/libs/*.jar
          retention-days: 1
